ho_blog:
    resource: "@HOBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

ho_member:
    resource: "@HOMemberBundle/Resources/config/routing.yml"
    prefix:   /member

ho_admin:
    resource: "@HOAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ho_shop:
    resource: "@HOShopBundle/Resources/config/routing.yml"
    prefix:   /

ho_core:
    resource: "@HOCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: HOUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout