# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    HO\UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_PREMIUM:     ROLE_USER
    ROLE_ADMIN:       [ROLE_USER, ROLE_PREMIUM, ROLE_ALLOWED_TO_SWITCH]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    HO\UserBundle\Entity\User
        property: username

  firewalls:
    api:
      pattern: ^/api
      anonymous: true
      stateless: true
      guard:
        authenticators:
          - 'jwt_token_authenticator'
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      provider:     main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: ho_core_homepage
        always_use_default_target_path: true
      logout:
        path:       logout
        target:     /

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }