<?php

namespace HO\MemberBundle\Repository;

/**
 * PremiumFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PremiumFileRepository extends \Doctrine\ORM\EntityRepository
{
}
