ho_blog_index:
    path:     /
    defaults: { _controller: HOBlogBundle:Blog:index }

ho_blog_view:
    path:    /view/{id}
    defaults: { _controller: HOBlogBundle:Blog:view }
    requirements: { id: \d }

ho_blog_add:
    path:    /add
    defaults: { _controller: HOBlogBundle:Blog:add }

ho_blog_edit:
    path:    /edit/{id}
    defaults: { _controller: HOBlogBundle:Blog:edit }
    requirements: { id: \d }

ho_blog_delete:
    path:    /delete/{id}
    defaults: { _controller: HOBlogBundle:Blog:delete }
    requirements: { id: \d }
